// @ts-check
import { defineConfig } from 'astro/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import tailwindcss from '@tailwindcss/vite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  site: 'https://nicovitolocksmith.com',
  // 'always' rather than 'ignore': every URL has exactly one valid form.
  // With 'ignore', /services/lock-rekeying and /services/lock-rekeying/ both
  // "work", the slashless one via a 307 — and Search Console was logging those
  // as "Page with redirect" because every internal link on the site pointed at
  // the slashless form.
  trailingSlash: 'always',
  build: { format: 'directory', inlineStylesheets: 'auto' },
  // Sitemaps are generated by scripts/sitemaps.mjs after the build, not by
  // @astrojs/sitemap: they need per-page lastmod driven by a content hash and
  // splitting by page type, neither of which the integration does.
  integrations: [],
  vite: {
    // Cast: @tailwindcss/vite resolves its own Vite copy, so its Plugin type
    // is structurally identical but nominally different from Astro's.
    plugins: [/** @type {any} */ (tailwindcss())],
    resolve: { alias: { '@': path.resolve(__dirname, './src') } },
  },
});
